FilmorateApp Sprint 10: initial commit
AleksandrTimofeev1987/java-filmorate pull request #2
Opened 2022-09-19 14:18 UTC by AleksandrTimofeev1987

refactor: перенести бизнес-логику в FilmStorage и UserStorage
feature: добавить операции с пользователями, как добавление в друзья, удаление из друзей, вывод списка общих друзей
feature: добавить операции с фильмами, — добавление и удаление лайка, вывод 10 наиболее популярных фильмов по количеству лайков
refactor: переделать код в контроллерах, сервисах и хранилищах под использование внедрения зависимостей
feature: довести API до соответствия REST
test: обвязать новый функционыл тестами

2022-09-20 13:58 UTC, Fleaman777 requested changes

2022-09-20 13:58 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        }
здорово, что сделал валидационные методы, а не просто вставил проверку в методы контроллера, 
но хорошо было бы все валидационные методы вынести в отдельный класс (спринг компонент)
тем самым разделить ответственность выполнения логики

2022-09-20 13:58 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private void validateUserExists(int user) {
здесь аналагично с FilmController

2022-09-20 13:58 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    public Film get(Integer id) {
а нужно ли создавать дополнительно метод get, когда есть, по сути, такой же getFilmById

2022-09-20 13:58 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        return String.format("Пользователю с id %d понравился фильм с id %d.", userId, filmId);
такая стринга будет удобна, если приложение взаимодействует с фронт энд частью и эта строка будет выведена на экран, 
но если такого жесткого требования нет, то на подобный запрос, лучше возвращать обновленный объект Film, тем самым, сервис который будет обращаться к нашему приложению, получит объект и сам решит, что с ним сделать: перевести в читаемый вид и отобразить его, или использовать как-то по-своему

т.к. в задании четкого требования на этот счет нет, то можешь просто принять к сведению, и оставить как есть 

аналагично в похожих местах

2022-09-20 13:58 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +                .collect(Collectors.toList());
отличный получился стрим

2022-09-20 13:58 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +    }
хороший метод для того, что бы сделать его через стрим

2022-09-20 13:58 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    public void givenInvalidUserIdWhenPutLikeThenStatus404andUserDoesNotExistException() throws Exception {
чаще всего я встречал вот такой вариант названия тест методов, 
например 
shouldReturn404OnPutLikeWhenInvalidUserId

такой формат, на мой взгляд и воспринимается полегче и выходит покороче

2022-09-20 15:59 UTC, AleksandrTimofeev1987 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        }
Согласен. Поправлю.

2022-09-20 16:00 UTC, AleksandrTimofeev1987 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    public Film get(Integer id) {
Да, и вправду. Вообще метод get как раз основной. Убрал метод getFilmById. Аналогично в UserService поправил.

2022-09-20 16:02 UTC, AleksandrTimofeev1987 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        return String.format("Пользователю с id %d понравился фильм с id %d.", userId, filmId);
Я так и хотел сделать, но вопрос возник при добавлении пользователей в друзья - в этом случае меняются оба пользователя и возник вопрос - кого возвращать. Как поступать в таком случае? Вернуть запрашивающего или список из обоих?

2022-09-21 16:36 UTC, Fleaman777 approved these changes

2022-09-22 06:26 UTC, merged